### ISSUE TITLE
AWS SSO with sessions

### ISSUE THREAD

**Issue by tfarkas86** [iterative/dvc-s3#37]
# Bug Report

## Description

AWS SSO currently uses both profiles and sessions. A link to the session is a configuration of the profile. The `sso_start_url` and `sso_region` are now found in the session, not profile, breaking DVCs sso authentication protocol for aws sso. 

### Reproduce

1. upgrade to aws cli v.2.*
2. export AWS_DEFAULT_PROFILE=dvc
3. aws configure sso --profile dvc
4. use session name = dvc, finish config wizard
5. dvc remote add s3-remote <some s3 location>
6. dvc add <some data>
7. dvc push -r s3-remote

### Expected

Should push to remote S3 location

### Environment information

AWS AMI2
aws-cli/2.11.4 
Python/3.11.2 
Linux/4.14.309-231.529.amzn2.x86_64 
exe/x86_64.amzn.2 prompt/off

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.52.0 (pip)
-------------------------
Platform: Python 3.9.16 on Linux-4.14.309-231.529.amzn2.x86_64-x86_64-with-glibc2.26
Subprojects:
	dvc_data = 0.46.0
	dvc_objects = 0.21.1
	dvc_render = 0.3.1
	dvc_task = 0.2.0
	scmrepo = 0.2.0
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.3.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: xfs on /dev/nvme1n1
Caches: local
Remotes: s3
Workspace directory: xfs on /dev/nvme1n1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/a384194e19be5dbbecf22402fcf32e7f
```

**Comment by shcheklein** [comment]
I think this should be fixed by now.
