### ISSUE TITLE
Unexpected argument when using `walk`

### ISSUE THREAD

**Issue by pared** [iterative/dvc-s3#5]
When running 
`dvc_s3/tests/test_dvc.py::TestImport::test_import_dir`
We get error on ubuntu machines:
https://github.com/iterative/dvc-s3/runs/7244289699

The culprit is the walk method:
https://github.com/iterative/dvc-objects/blob/cd32e606091b2b8191d1bf62fb9f2026fd25e5e0/src/dvc_objects/fs/base.py#L400
Which passes the `topdown` argument.
The reason why it shows up only now is that we used to use `find` when building a tree in `dvc-data` and we changed it in:
https://github.com/iterative/dvc-data/pull/78
to `walk`.

The first idea is to adjust `S3FileSystem._ls` to accept `kwargs` which it does not now:
https://github.com/fsspec/s3fs/blob/3e9b7d4a62f6efb3d282d9ded2baf4625fab0515/s3fs/core.py#L844
as other implementations of fsspec seem to do.

Need some further research if this is the right thing to do.

**Comment by efiop** [comment]
Looks like just need to remove that topdown from base, as it is not supported by fsspec and we are not using it anyway

**Comment by pared** [comment]
> as it is not supported by fsspec
That's what has been missing in my research :)
